static_library("103_traffic_demo") {
  sources = [ 
    "main.c",
    "./key/key_demo.c",
    "./segment_display/segment_display.c",
    "./traffic_light/traffic_light.c",
  ]

  include_dirs = [
    "//device/soc/hisilicon/ws63v100/sdk/middleware/utils/app_init",
    "//device/soc/hisilicon/ws63v100/sdk/kernel/osal/include/debug",
    "//device/soc/hisilicon/ws63v100/sdk/kernel/osal/include/memory",
    "//device/soc/hisilicon/ws63v100/sdk/include/driver",
    "//device/soc/hisilicon/ws63v100/sdk/drivers/drivers/hal/gpio",
    "//device/soc/hisilicon/ws63v100/sdk/drivers/chips/ws63/porting/gpio",
    "//device/soc/hisilicon/ws63v100/sdk/drivers/drivers/hal/gpio/v150",
    "//device/soc/hisilicon/ws63v100/sdk/drivers/chips/ws63/porting/pinctrl",
    "//device/soc/hisilicon/hi3516dv300/sdk_liteos/include",

    "//utils/native/lite/include",
    "//kernel/liteos_m/kal",
    "//base/iot_hardware/peripheral/interfaces/kits",
    "//base/iothardware/peripheral/interfaces/inner_api",
  ]
} 